export const meta = {
  name: 'm-fit-2',
  description: 'M(fit-2): the qpAdm RANK TEST / qpWave ON THE GPU — the rank sweep (ranks 0..nl-1) + chi^2/dof/p per rank + nested rankdrop + popdrop (leave-one-source-out), extending the M(fit-4) GPU SVD seed. Validated vs the AT2 rankdrop/popdrop goldens (the existing 9-pop golden_fit0; pin an nr>32 fixture if feasible to exercise the per-model gesvd fallback vs the nr<=32 gesvdjBatched path). RULE (the user, emphatic): the CpuBackend is a DEDICATED PARITY step ONLY (the native oracle) — reaching parity on it is just one step; the milestone is NOT complete until the GPU version is built and working. The GPU implementation is the COMPLETENESS GATE — the final step before the independent verdict. Design -> CPU-parity (oracle) -> GPU (the deliverable) -> INDEPENDENT verdict (the GPU rank test matches the AT2 goldens RUNNING ON THE GPU). commit-green / revert+HALT.',
  phases: [
    { title: 'Design', detail: 'freeze the GPU rank-test/qpWave/rankdrop/popdrop contract + the golden plan (reuse 9-pop goldens; nr>32 feasibility); read-only' },
    { title: 'CPU-parity', detail: 'CpuBackend rank sweep + rankdrop + popdrop validated vs the AT2 goldens — the native ORACLE (parity step only, NOT the deliverable); pin an nr>32 golden if feasible' },
    { title: 'GPU', detail: 'the rank test ON THE GPU (cuSOLVER gesvd/gesvdjBatched, the sweep, chi^2/dof/p, batched rankdrop/popdrop), resident f2 — THE deliverable / completeness gate' },
    { title: 'Verify', detail: 'independent verdict: the GPU rank test matches the AT2 rankdrop/popdrop goldens RUNNING ON THE GPU (not CpuBackend); build/ctest green; commit-green / revert+HALT' },
  ],
}

const R = '/home/suzunik/steppe'
const SSH = 'ssh box5090'
const PATHENV = 'export PATH=/usr/local/cuda/bin:$PATH && export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH && ulimit -c 0'
const RSYNC = 'rsync -az --delete-after --exclude .git --exclude build --exclude build-rel --exclude aadr -e ssh ' + R + '/ box5090:/workspace/steppe/'
const BUILD = SSH + " 'cd /workspace/steppe && " + PATHENV + " && cmake -S . -B build-rel -GNinja -DCMAKE_BUILD_TYPE=Release >/tmp/cfg.log 2>&1 && cmake --build build-rel 2>&1 | tail -30 && echo === CTEST === && ctest --test-dir build-rel --output-on-failure 2>&1 | tail -45'"
const QPTEST = SSH + " 'cd /workspace/steppe && export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH && ulimit -c 0 && ctest --test-dir build-rel -R qpadm --output-on-failure 2>&1 | tail -80'"
const CLEAN = 'cd ' + R + ' && git checkout -- . && git clean -fd src tests include docs'

const STD = [
  'PROJECT: steppe = GPU/CUDA-13/Blackwell (sm_120) reimplementation of ADMIXTOOLS 2. Phase-2 qpAdm fit engine. Branch phase2-fit-engine @ 8ace724 (== main; the fit slice merged). DONE: M(fit-1) the GLS weight fit (CpuBackend, parity vs the af6a8c2 golden), M(fit-4) the qpAdm fit ON THE GPU (CUDA backend: f4-gather from resident DeviceF2Blocks, jackknife Q via cublasDsyrk, rank-SVD seed + ALS, GLS weights, batched LOO SE), the cuSOLVER solve promotion seam (d6d3cbb), and the UNIFIED precision policy (8ace724: default EmulatedFp64{40}, native fallback, cancellation + cuSOLVER-solve carve-outs native).',
  'HARD RULE (the user, emphatic; memory build-the-real-gpu-implementation): you MAY use the CpuBackend as a DEDICATED PARITY step — it is the native ORACLE the test diffs against. BUT reaching parity on the CPU is ONLY ONE STEP. The milestone is NOT COMPLETE until the GPU version is built and working. The GPU implementation is the COMPLETENESS GATE — "the final step before verification in our workflow." So: build the CPU rank test for parity (oracle), THEN build it ON THE GPU (the deliverable), THEN the independent verdict gates on the GPU version matching the goldens RUNNING ON THE GPU. NEVER report the CPU result as the deliverable.',
  'WHAT M(fit-2) BUILDS (fit-engine.md §3 M(fit-2); SPEC §5:221/§5:231): the qpAdm RANK TEST / qpWave — (1) the RANK SWEEP: for each candidate rank r in 0..nl-1, the rank-r factorization (svd(X) seed -> Q-weighted ALS, reusing the M(fit-4) machinery) and the GLS residual quadratic-form test statistic chi^2(r) = vec(E_r)^T Q^{-1} vec(E_r), dof(r), p(r) = pchisq(chi^2, dof); (2) the NESTED RANKDROP table (AT2 res$rankdrop): chisqdiff/dofdiff between consecutive ranks -> the smallest non-rejected rank (f4rank); (3) the POPDROP table (AT2 res$popdrop): leave-one-LEFT-source-out feasibility (drop each left pop, refit, report); (4) qpWave: the rank-sufficiency test for whether the nl left pops are consistent with rank r (the same rankdrop machinery without a target). The rank_test virtual exists today only as the SVD SEED for the M(fit-4) fit (backend.hpp:539, cpu_backend.cpp:490, cuda_backend.cu:1468) — EXTEND it (or add a sibling rank_sweep/qpwave virtual) to produce the full sweep + rankdrop + popdrop.',
  'DISPATCH (SPEC §5:231): the rank SVD is gesvdjBatched when nl,nr <= 32 (the batched path), else per-model gesvd (the fallback) — orient X so rows>=cols (gesvd deterministic only for m>n). gesvda is EXCLUDED (screening only). The 9-pop golden is nr=6 (<=32, batched). REPORT which path each fixture takes.',
  'GOLDENS (the acceptance oracle, §12/§13; NO synthetic data for any accuracy claim — REAL AADR only): the 9-pop AT2 goldens ALREADY EXIST and carry the rank-test fields — tests/reference/goldens/at2/golden_fit0.json (chisq, chisqdiff, dof, dofdiff, f4rank, rankdrop, popdrop, rank_Q) + csv/golden_fit0_rankdrop.csv + csv/golden_fit0_popdrop.csv. Use these as the PRIMARY gate (nr<=32 batched path). The nr>32 gesvd FALLBACK has NO fixture yet: in CPU-parity, pin an nr>32 AT2 golden IF FEASIBLE (R + admixtools were installed for M(fit-0) — extract_f2 on real AADR for a model with >32 right pops + qpadm/qpwave, capturing rankdrop, full §12 metadata). If pinning a clean nr>32 golden is infeasible/blocked, proceed with the 9-pop gate and mark the nr>32 path "dispatch implemented + run, golden PENDING" (do NOT fabricate an nr>32 golden, do NOT claim nr>32 accuracy without a real golden).',
  'PRECISION (the UNIFIED policy, 8ace724 / fit-engine.md §1.4): default EmulatedFp64{40} for the well-conditioned matmul-heavy work (the covariance SYRK, any GLS GEMMs), NATIVE fallback via emulation_honorable; the cancellation-sensitive f-stat diffs stay native (carve-out); the rank SVD + the Q^{-1} / chi^2 quadratic form are cuSOLVER/ill-conditioned -> NATIVE (cuSOLVER has NO FP64-emulated mode on this toolkit; the d6d3cbb seam auto-promotes the solves later). Match the CPU oracle exactly.',
  'GATE (must-pass): the GPU (CUDA backend) rank test for the 9-pop model reproduces the AT2 goldens: f4rank exact, dof/dofdiff exact, chisq/chisqdiff within the tight tier (rtol~1e-6 to the golden chisq), p / the rank decision within the loose tier (rtol~1e-3 / the same accept/reject), the rankdrop + popdrop tables matching AT2 row-for-row; the fit RUNS ON THE GPU (cuSOLVER/kernels, f2 resident, no host round-trip). The test (tests/reference/test_qpadm_parity.cu) must exercise the CUDA backend rank test (assert GPU path) and diff the CpuBackend ONLY as the oracle/localizer. Report the nr<=32 (batched) and, if pinned, nr>32 (fallback) results.',
  'BOX = box5090 (vast 2x RTX 5090, UP, sm_120, CUDA 13). ' + SSH + ' (alias); nvcc -> ' + PATHENV + ' . build-rel exists. RELEASE only. NOTHING builds locally. The 9-pop fixture (tests/reference/goldens/at2/fixtures/f2_fit0_9pop.bin) + AADR + R/admixtools are on the box.',
  'KEY FILES: src/device/backend.hpp (the rank_test virtual @539 — extend / add rank_sweep+qpwave+rankdrop+popdrop), src/core/qpadm/{ranktest,nested_models,qpadm_fit}.* + a NEW ranktest unit if warranted (host-pure orchestration through ComputeBackend), src/device/cpu/cpu_backend.cpp (the native ORACLE rank sweep — the parity step), src/device/cuda/cuda_backend.cu + qpadm_fit_kernels.cu/.cuh (the GPU rank sweep — THE deliverable: cuSOLVER gesvd/gesvdjBatched dispatch, batched chi^2/dof/p, batched rankdrop/popdrop), tests/reference/test_qpadm_parity.cu (extend: the GPU rank test vs the AT2 rankdrop/popdrop goldens), tests/reference/goldens/at2/* (the goldens; add an nr>32 fixture if pinned), docs/design/fit-engine.md (M(fit-2) row).',
].join('\n')

const DEVLOOP = 'DEV LOOP: edit locally; rsync (' + RSYNC + '); RELEASE build+ctest (' + BUILD + '); the qpAdm test (' + QPTEST + '). Do NOT commit (the verdict commits). Clean revert: ' + CLEAN + '.'

phase('Design')
const design = await agent([
  'You are the lead architect freezing the M(fit-2) contract: the qpAdm RANK TEST / qpWave ON THE GPU (the rank sweep + chi^2/dof/p + nested rankdrop + popdrop), CPU-parity-then-GPU. READ-ONLY (read backend.hpp rank_test @539, cpu_backend.cpp:490 + cuda_backend.cu:1468 rank_test seed, the M(fit-4) GPU SVD/ALS in qpadm_fit_kernels.cu, nested_models.*, qpadm_fit.*, the goldens golden_fit0.json + rankdrop/popdrop csv, test_qpadm_parity.cu, fit-engine.md §3 M(fit-2)/§1.4; do NOT edit, do NOT touch the box).', STD, '',
  'Specify with file:line + signatures: (1) the rank-sweep / qpwave / rankdrop / popdrop API on ComputeBackend (extend rank_test or add siblings) — the exact returned structs (per-rank chi^2/dof/p; the rankdrop table f4rank/chisqdiff/dofdiff; the popdrop table) and how they map to the AT2 golden_fit0 fields; (2) the GPU rank-SVD dispatch (gesvdjBatched nl,nr<=32 vs per-model gesvd fallback, X oriented rows>=cols, determinism) reusing the M(fit-4) cuSOLVER plumbing; (3) the batched chi^2 = vec(E_r)^T Q^{-1} vec(E_r) per rank + the nested chisqdiff/dofdiff; (4) the precision map (unified policy: SVD/Q^{-1}/chi^2 native; well-conditioned matmuls emulated{40} default); (5) the golden plan — confirm the 9-pop rankdrop/popdrop goldens suffice for the nr<=32 gate, and STATE whether an nr>32 AT2 golden should be pinned in CPU-parity (feasibility on the box R/admixtools env) to exercise the gesvd fallback; (6) the CPU-parity step (CpuBackend rank sweep = the native oracle) and the GPU step (the deliverable) split, and the test extension asserting the GPU path. The implementers make NO design decisions. GPU-first; the CpuBackend is the oracle, NOT the deliverable.',
].join('\n'), { label: 'design:rank-test', phase: 'Design' })

phase('CPU-parity')
const cpu = await agent([
  'You are a senior engineer building the CpuBackend rank test as the NATIVE ORACLE for parity — a DEDICATED PARITY STEP, explicitly NOT the deliverable (the GPU version, next phase, is the deliverable/completeness gate). Implement the rank sweep + rankdrop + popdrop on the CpuBackend (native FP64), validate it vs the AT2 9-pop goldens, and (IF FEASIBLE) pin an nr>32 AT2 golden on the box. EDIT locally + dev-loop on box5090; do NOT commit.', STD, '',
  'THE FROZEN DESIGN:\n<<<\n' + (design || '(missing — derive from backend.hpp rank_test + the M(fit-4) CPU rank seed; implement the full sweep/rankdrop/popdrop on CpuBackend, native FP64)') + '\n>>>', '', DEVLOOP, '',
  'Build the CpuBackend rank sweep (ranks 0..nl-1: chi^2/dof/p), the nested rankdrop (f4rank/chisqdiff/dofdiff), and the popdrop (leave-one-source-out). Validate vs golden_fit0.json + rankdrop/popdrop csv (f4rank exact, dof/dofdiff exact, chisq/chisqdiff rtol~1e-6, p/rank-decision loose, tables row-for-row). IF the R/admixtools env on the box makes it feasible, ALSO pin an nr>32 AT2 golden (extract_f2 on REAL AADR for a >32-right model + qpadm/qpwave rankdrop, full §12 metadata) into tests/reference/goldens/at2/ — REAL data only; if infeasible, say so and proceed (the nr>32 golden is non-gating). Report: git diff --stat; the CPU rank-test-vs-golden results (per-rank + the tables); whether an nr>32 golden was pinned (+ its values/metadata) or why not. Do NOT commit. This is the ORACLE, not the deliverable — do NOT stop here.',
].join('\n'), { label: 'impl:rank-test-cpu', phase: 'CPU-parity' })

phase('GPU')
const gpu = await agent([
  'You are a senior CUDA engineer building THE DELIVERABLE: the qpAdm rank test ON THE GPU (CUDA backend) — the completeness gate, the final implementation step before the independent verdict. The CpuBackend rank test from the previous phase is the native ORACLE you diff against; it is NOT the deliverable. Implement the rank sweep + rankdrop + popdrop on the CUDA backend, reading f2 RESIDENT, matching the CPU oracle + the AT2 goldens. EDIT locally + dev-loop on box5090; do NOT commit.', STD, '',
  'THE FROZEN DESIGN:\n<<<\n' + (design || '(missing)') + '\n>>>', '',
  'THE CPU-PARITY (ORACLE) REPORT:\n<<<\n' + (cpu || '(cpu phase died — proceed: build the GPU rank test against the AT2 goldens directly, CpuBackend as the diff oracle)') + '\n>>>', '', DEVLOOP, '',
  'Build the GPU rank sweep: cuSOLVER gesvd/gesvdjBatched dispatch (nr<=32 batched vs nr>32 per-model fallback, X rows>=cols, deterministic, single statistic stream), the batched per-rank chi^2 = vec(E_r)^T Q^{-1} vec(E_r) / dof / p, the nested rankdrop, the popdrop — all reading DeviceF2Blocks RESIDENT, batched-capable, precision per the unified policy (SVD/Q^{-1}/chi^2 native; well-conditioned matmuls emulated{40}). Extend test_qpadm_parity.cu to exercise the CUDA-backend rank test (assert GPU path) vs the AT2 rankdrop/popdrop goldens (CpuBackend ONLY as the diff oracle). Iterate until: build clean (warnings-as-errors), full ctest green, AND the GPU rank test matches the AT2 goldens (f4rank exact, dof/dofdiff exact, chisq/chisqdiff rtol~1e-6, p/rank-decision loose, tables row-for-row) RUNNING ON THE GPU (cuSOLVER/kernels, f2 resident). Report: git diff --stat; the GPU rank-test-vs-golden results (per-rank + rankdrop + popdrop); the nr<=32 (batched) and, if a golden was pinned, nr>32 (fallback) dispatch + results; confirmation it ran on the GPU. Do NOT commit. If a quantity diverges on the GPU, localize with the CPU oracle and report the real delta — do NOT fabricate, do NOT loosen tiers.',
].join('\n'), { label: 'impl:rank-test-gpu', phase: 'GPU' })

const VERDICT_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['pass','diff_is_real','runs_on_gpu','resident_no_roundtrip','f4rank_exact','dof_exact','chisq_match','tables_match','dispatch_reported','nr_gt32_status','gpu_results','commit_hash','note'],
  properties: {
    pass: { type: 'boolean', description: 'true ONLY if: real diff implementing the CUDA-backend rank sweep/rankdrop/popdrop (cuSOLVER gesvd/gesvdjBatched + batched chi^2 + kernels) + Release build clean + full ctest green + the GPU rank test matches the AT2 9-pop goldens (f4rank exact, dof/dofdiff exact, chisq/chisqdiff rtol~1e-6, p/rank-decision loose, rankdrop+popdrop tables row-for-row) + the fit genuinely runs ON THE GPU reading f2 resident (NOT the CpuBackend). The CpuBackend rank test may also be present (the oracle) but is NOT what passes.' },
    diff_is_real: { type: 'boolean', description: 'you re-ran git diff: the CUDA-backend rank sweep is genuinely present (real cuSOLVER SVD dispatch + batched chi^2/rankdrop/popdrop), not a stub or a CpuBackend passthrough' },
    runs_on_gpu: { type: 'boolean', description: 'the parity test exercises the CUDA backend rank test (you confirmed GPU cuSOLVER/kernels, not the CpuBackend)' },
    resident_no_roundtrip: { type: 'boolean', description: 'the rank test reads f2_blocks RESIDENT (DeviceF2Blocks); no per-model host round-trip of f2' },
    f4rank_exact: { type: 'boolean', description: 'the GPU f4rank (smallest non-rejected rank) == the AT2 golden f4rank exactly' },
    dof_exact: { type: 'boolean', description: 'dof + dofdiff exact vs the golden' },
    chisq_match: { type: 'boolean', description: 'chisq + chisqdiff within rtol~1e-6 of the golden' },
    tables_match: { type: 'boolean', description: 'the rankdrop + popdrop tables match AT2 row-for-row (within tier)' },
    dispatch_reported: { type: 'boolean', description: 'the gesvdjBatched (nr<=32) vs gesvd (nr>32) dispatch path is reported per fixture' },
    nr_gt32_status: { type: 'string', description: 'the nr>32 fallback: golden PINNED + matched (with values), or dispatch-implemented + golden PENDING (honest — no fabricated nr>32 golden / no accuracy claim without a real golden)' },
    gpu_results: { type: 'string', description: 'the YOU-measured GPU-path rank-test results (per-rank chi^2/dof/p + f4rank + the rankdrop/popdrop tables) vs the golden' },
    commit_hash: { type: 'string' },
    note: { type: 'string', description: 'GPU-path steppe-vs-golden per quantity + confirmation it ran on the GPU resident; for FAIL exactly what diverged or where it fell back to CPU' },
  },
}
phase('Verify')
const verdictPrompt =
  'You are the INDEPENDENT VERDICT (maximally adversarial — the user is emphatic the milestone is COMPLETE only when the GPU version works, not when CPU parity is reached; prior fix-passes have shammed). The GPU implementer reported:\n<<<\n' + (gpu || '(gpu phase died)') + '\n>>>\n\nThe CPU-parity (oracle) report:\n<<<\n' + (cpu || '(cpu phase died)') + '\n>>>\n\n' + STD + '\n\n' +
  'DO, yourself: (1) cd ' + R + ' && git --no-pager diff --stat && git --no-pager diff — CONFIRM the CUDA-backend rank sweep/rankdrop/popdrop is genuinely present (real cuSOLVER gesvd/gesvdjBatched dispatch + batched chi^2 + the tables) reading DeviceF2Blocks resident — NOT a stub, NOT a CpuBackend passthrough, NOT a CPU result dressed up as GPU. If the rank test secretly runs on the CpuBackend => pass=false. (2) RE-RUN yourself: ' + BUILD + ' ; ' + QPTEST + ' . (3) PASS only if ALL: diff real (GPU cuSOLVER/kernels); Release build clean; full ctest green; the GPU rank test matches the AT2 9-pop goldens (f4rank exact, dof/dofdiff exact, chisq/chisqdiff rtol~1e-6, p/rank-decision loose, rankdrop+popdrop row-for-row); AND you confirm it ran ON THE GPU reading f2 RESIDENT (inspect the test/code — it must dispatch to the CUDA backend). The nr>32 fallback is REPORTED (nr_gt32_status), non-gating. NO tier was loosened. \n\nON PASS: cd ' + R + ' && git add ONLY the genuinely-new/changed source+test+doc+golden files (NEVER git add dot; never aadr/ build_run.sh f2_emu_spike.cu handoff-*.md); commit with a ROADMAP §6 message (M(fit-2) the qpAdm rank test/qpWave on the GPU + the measured vs-golden rankdrop/popdrop parity) ending: Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com> . Capture the hash.\nON FAIL: ' + CLEAN + ' ; report exactly what diverged or where it fell back to CPU.\nReturn the structured verdict.'

async function tryAgent(p, opts) {
  let r = await agent(p, opts)
  if (r === null) { log(opts.label + ': transient null — retry once'); r = await agent(p, { ...opts, label: opts.label + ':retry' }) }
  return r
}
const verdict = await tryAgent(verdictPrompt, { schema: VERDICT_SCHEMA, label: 'verdict:rank-test', phase: 'Verify' })

if (verdict && verdict.pass) log('+++ M(fit-2) RANK TEST ON GPU LANDED ' + verdict.commit_hash + ' — runs_on_gpu=' + verdict.runs_on_gpu + ' f4rank_exact=' + verdict.f4rank_exact + ' tables_match=' + verdict.tables_match + ' nr>32=' + verdict.nr_gt32_status + ' | ' + verdict.gpu_results)
else log('--- M(fit-2) FAILED (' + (verdict ? verdict.note : 'agent died') + ') — HALT; human takes over')
return { design, cpu, gpu, verdict }
