export const meta = {
  name: 'qpfstats-build',
  description: 'BUILD qpfstats (STEP 3, tool 1 of 3 — the roadmap, per docs/research/qpfstats-gpu-design.md). qpfstats = the admixtools joint full-basis f-stat estimator with shrinkage/smoothing (estimate ALL f2/f3/f4 jointly from a regularized full covariance, more accurate than per-stat estimates). REQUIREMENTS (user, restated + locked): GPU-FIRST + GPU-BOUND (adapt to steppe GPU shape, do NOT transliterate the AT2 CPU topology — AT2 qpfstats is a HOST loop over ~1300 jackknife blocks doing per-block triangular solves + Cholesky downdates [the CPU-bound trap]; REFORMULATE to ONE shared-factor cuSOLVER potrf + a single batched potrsBatched/Dtrsm over the whole [npair x nblock] RHS, NaN/missing blocks grouped by a CUB segmented mask + per-group re-factor — the primitive is already proven at cuda_backend.cu potrfBatched/potrsBatched/gemmStridedBatched). VERIFY (real code file:line + the admixtools qpfstats method/source). REUSE the existing seams, NO parallel bolt-on (the solve/precision seam set_solve_precision + CusolverMathModeScope; small_linalg.hpp as the CpuBackend oracle; the f2 cache F2BlockTensor + read_f2_dir; jackknife_cov; the CLI/binding scaffold). EMULATED-FP64 FIRST (EmulatedFp64{40} default for the matmul-heavy covariance/solve, native carve-out for cancellation; reuse engage_*/emulation_honorable). SINGLE-GPU --device 0 (multi-GPU PARKED). CUDA 13+ (verify cuSOLVER/cuBLAS/CUB APIs vs the docs). KEEP ON-DEVICE — no warts, no host data-bouncing (the big covariance + the long-format frame stay device-resident; do NOT materialize the hundreds-of-GB host frame AT2 warns about). ORACLE = admixtools-R qpfstats() (consistent with every other steppe golden — regenerate a FIXTURE-MATCHED golden from read_f2 of the real f2, like the f4/f3 goldens; no-AT2 lifted for golden GENERATION only). DELIVER: a run_qpfstats core entry + a `steppe qpfstats` CLI + a steppe.qpfstats binding + a CpuBackend oracle + the golden gate (rtol the tier). Discipline: design+regen-golden (GATE) -> implement (oracle-first then on-device) -> verify (golden + GPU-bound + emulated + ctest) -> commit. FAIL-PROTOCOL: verify->commit on green; on BAD -> HALT + report (defer to the user), NEVER silently fail or revert; on failure git stash push -u + HALT (do NOT git checkout/clean).',
  phases: [ { title: 'Design + regen the qpfstats golden (GATE: GPU shape + oracle + reuse)' }, { title: 'Implement run_qpfstats (oracle-first + on-device) + CLI + binding + build' }, { title: 'Verify golden + GPU-bound + emulated + commit-or-HALT' } ],
}

const R = '/home/suzunik/steppe'
const SSH = 'ssh box5090'
const PATHENV = 'export PATH=/usr/local/cuda/bin:$PATH && export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH && ulimit -c 0'
const CORECLEAN = 'rm -f /var/lib/vastai_kaalia/data/core-* 2>/dev/null'
const RSYNC = 'rsync -az --delete-after --exclude .git --exclude build --exclude build-rel --exclude aadr --exclude atlas_results -e ssh ' + R + '/ box5090:/workspace/steppe/'
const PULL = 'rsync -az -e ssh box5090:/workspace/steppe/tests/reference/goldens/at2/ ' + R + '/tests/reference/goldens/at2/'
const BUILD = SSH + " 'cd /workspace/steppe && " + PATHENV + " && " + CORECLEAN + " && cmake -S . -B build-rel -GNinja -DCMAKE_BUILD_TYPE=Release -DSTEPPE_BUILD_CLI=ON -DSTEPPE_BUILD_PYTHON=ON >/tmp/cfg.log 2>&1 && cmake --build build-rel 2>&1 | tail -25 && echo === CTEST === && STEPPE_THOROUGH=1 ctest --test-dir build-rel --output-on-failure 2>&1 | tail -25; " + CORECLEAN + "'"
const STASH = 'cd ' + R + ' && git stash push -u -m'
const PA = '/workspace/data/aadr/converted_pa/v66_HO_pa'

const STD = [
  'PROJECT: steppe = GPU/CUDA-13 reimplementation of ADMIXTOOLS 2 + qpAdm. Branch phase2-fit-engine == main @ 41942ed. BUILT: the fit engine + the standalone f-stats (f4/f3/f4-ratio/qpDstat) + the GPU sweep + Python bindings + the wheel. The qpfstats GPU-shape design is docs/research/qpfstats-gpu-design.md; the reusable seams are mapped in docs/research/code-inventory-for-new-tools.md.',
  'STANDING REQUIREMENTS (user, locked): (1) GPU-FIRST + GPU-BOUND — adapt the algorithm to steppe GPU shape, NEVER transliterate the AT2 CPU topology; if the textbook form is a host loop, REFORMULATE it on-device. (2) VERIFY everything (real code file:line + the admixtools qpfstats method) before asserting. (3) REUSE the existing seams, NO parallel bolt-on. (4) EmulatedFp64 first (native fallback + cancellation carve-out). (5) SINGLE-GPU --device 0 (multi-GPU PARKED, 5090 no P2P). (6) CUDA 13+ — verify cuSOLVER/cuBLAS/CUB APIs vs the docs. (7) KEEP ON-DEVICE — no warts, no host data-bouncing. (8) verify->commit on green; on BAD HALT + ask, NEVER silently fail/revert.',
  'THE CPU-BOUND TRAP (from the design doc, designed out): AT2 qpfstats_regression is a HOST loop over ~1300 jackknife blocks doing per-block triangular solves + Cholesky downdates (the exact f-stat-sweep-disaster shape). REFORMULATE: ONE shared-factor cuSOLVER potrf + a SINGLE batched potrsBatched/Dtrsm over the whole [npair x nblock] RHS; NaN/missing blocks grouped by a CUB segmented mask + per-group re-factor (never a host branch). The big covariance / long-format frame stays DEVICE-RESIDENT (do NOT materialize the hundreds-of-GB host frame AT2 warns about). Reuse cuda_backend.cu potrfBatched/potrsBatched/gemmStridedBatched + the solve/precision seam.',
  'ORACLE (no open decision): admixtools-R qpfstats() — CONSISTENT with every other steppe golden (golden_fit0, the f4/f3 readf2 goldens were all admixtools-R from read_f2). On box5090 (AT2/R, no-AT2 lifted for GENERATION only): regenerate a FIXTURE-MATCHED golden via admixtools::qpfstats(read_f2(the 9-pop convertf-PA f2 == the committed fixture f2_fit0_9pop.bin), ...) -> golden_fit0_qpfstats_readf2.csv. PROVE fixture-consistency (steppe qpfstats-from-the-fixture-f2 == the golden to the tier) before trusting it. If the admixtools-R qpfstats output is ambiguous/irreproducible (the C-doscale vs R-ridge divergence the design flagged), HALT + report (do NOT guess).',
  'REUSE (verify file:line, no dup): set_solve_precision (backend.hpp) + CusolverMathModeScope (handles.hpp); the cuSOLVER/cuBLAS batched primitives (cuda_backend.cu potrfBatched/potrsBatched/gemmStridedBatched); small_linalg.hpp (the CpuBackend oracle); F2BlockTensor + read_f2_dir + DeviceF2Blocks (the resident f2); jackknife_cov; the CLI flag helpers + the cmd_f4/cmd_qpdstat pattern; the result emitter; the nanobind module. New = the qpfstats joint estimator (the shared-factor batched solve + shrinkage) + run_qpfstats + cmd_qpfstats + the binding.',
  'FAIL-PROTOCOL (USER-MANDATED, STRICT): NEVER git checkout -- . / git clean -fd. verify->commit ONLY on green. On a BAD result (golden mismatch beyond tier, CPU-bound, structural blocker, oracle ambiguity) HALT + report + DEFER to the user — do NOT silently fail, do NOT revert without asking. On any failure ' + STASH + ' "wip:qpfstats-FAILED-<reason>" + HALT.',
  'SINGLE-GPU --device 0. RELEASE build-rel. REAL AADR; no synthetic. convertf-PA at ' + PA + '. Box ' + SSH + '; nvcc -> ' + PATHENV + '. §4 layering (cmd/binding TUs CUDA-free; kernels in .cu). nothing builds locally.',
].join('\n')

async function tryAgent(p, opts) { let r = await agent(p, opts); for (let i=0;i<2&&r===null;i++){ log(opts.label+': transient null/500 — retry '+(i+1)); r = await agent(p, {...opts, label: opts.label+':retry'+(i+1)}) } return r }

phase('Design + regen the qpfstats golden (GATE: GPU shape + oracle + reuse)')
const DESIGN_SCHEMA = {
  type: 'object', additionalProperties: false, required: ['feasible','gpu_shape','cpu_trap_designed_out','oracle_golden','fixture_match_check','reuse','emulated_plan','cuda13_apis','design','blocker','notes'],
  properties: {
    feasible: { type: 'boolean', description: 'true iff qpfstats is buildable GPU-bound (the shared-factor batched solve, no host per-block loop), reusing the existing seams, with a reproducible fixture-matched admixtools-R golden. false -> HALT + defer' },
    gpu_shape: { type: 'string', description: 'the GPU-bound design adapted to steppe shape (NOT the AT2 host-block-loop): the shared-factor potrf + batched potrsBatched over [npair x nblock], device-resident covariance, file:line for the reused primitives' },
    cpu_trap_designed_out: { type: 'string', description: 'EXPLICITLY: the AT2 host-block-loop trap + how this design keeps it on-device (no host per-block solve; the NaN-block CUB-segmented grouping; no host frame materialization)' },
    oracle_golden: { type: 'string', description: 'the regenerated fixture-matched golden_fit0_qpfstats_readf2.csv (path + sample) via admixtools-R qpfstats(read_f2(...)); or, if the oracle is ambiguous, feasible=false + the ambiguity' },
    fixture_match_check: { type: 'string', description: 'PROOF the golden matches the read_f2 fixture normalization (steppe qpfstats-from-fixture vs the golden ~ the tier)' },
    reuse: { type: 'string', description: 'the exact existing seams reused (file:line) — no parallel bolt-on' },
    emulated_plan: { type: 'string', description: 'where EmulatedFp64{40} (matmul-heavy covariance/solve) vs native carve-out (cancellation), via engage_*/emulation_honorable' },
    cuda13_apis: { type: 'string', description: 'the cuSOLVER/cuBLAS/CUB APIs VERIFIED vs CUDA 13.x docs (potrfBatched/potrsBatched/segmented-select)' },
    design: { type: 'string', description: 'the run_qpfstats plan (the joint estimator + shrinkage; the CLI + binding)' },
    blocker: { type: 'string', description: 'if NOT feasible: the structural blocker / oracle ambiguity + options (HALT + defer)' },
    notes: { type: 'string' },
  },
}
const design = await tryAgent([
  'You are designing qpfstats GPU-first + regenerating its golden (verify-before-implement; NO steppe code changes). READ docs/research/qpfstats-gpu-design.md + code-inventory-for-new-tools.md, the admixtools qpfstats method (web github uqrmaie1/admixtools qpfstats + the box AdmixTools C qpfstats.c + qpfs.pdf if present), the reusable seams (cuda_backend.cu potrfBatched/potrsBatched/gemmStridedBatched + set_solve_precision; small_linalg.hpp; F2BlockTensor/read_f2_dir; jackknife_cov; cmd_f4/cmd_qpdstat + the emitter + the nanobind module). VERIFY the cuSOLVER/cuBLAS/CUB APIs vs the CUDA 13.x docs. On box5090 (AT2/R, lifted no-AT2 for GENERATION): regenerate golden_fit0_qpfstats_readf2.csv via admixtools-R qpfstats(read_f2(the 9-pop convertf-PA f2 == the fixture)); PROVE fixture-consistency; pull ' + PULL + ' . Design run_qpfstats GPU-bound (the shared-factor batched solve, NO host per-block loop, device-resident, emulated-FP64). Return the structured design. If qpfstats cannot be GPU-bound by reuse OR the admixtools-R oracle is ambiguous/irreproducible, set feasible=false + blocker (HALT + defer, do NOT guess).', STD,
].join('\n'), { schema: DESIGN_SCHEMA, label: 'design:qpfstats', phase: 'Design + regen the qpfstats golden (GATE: GPU shape + oracle + reuse)' })
if (design === null) { log('--- design died — HALT'); return { halted: true } }
if (!design.feasible) { log('--- qpfstats STRUCTURAL/oracle-ambiguous (HALT + defer): ' + design.blocker); return { halted: true, deferred: true, design } }
log('qpfstats feasible GPU-bound; oracle golden: ' + String(design.fixture_match_check).slice(0,120))

phase('Implement run_qpfstats (oracle-first + on-device) + CLI + binding + build')
const fixer = await tryAgent([
  'You are implementing qpfstats per this design (GPU-bound, reuse-no-bolt-on, emulated-first, on-device-no-bounce):\n<<<\n' + JSON.stringify(design) + '\n>>>\n\nDo NOT commit. Do NOT git checkout/clean (git stash if forced).', STD, '', 'DEV LOOP: edit locally; ' + RSYNC + '; build+ctest (' + BUILD + ').', '',
  'IMPLEMENT: a CpuBackend oracle run_qpfstats (small_linalg, native — the reference) FIRST, then the on-device GPU-bound path (the shared-factor potrf + batched potrsBatched over [npair x nblock], device-resident covariance, emulated-FP64 matmul + native cancellation carve-out, NaN-block CUB-segmented grouping — NO host per-block loop, NO host frame materialization); reuse the solve/precision seam + the batched cuSOLVER primitives (no dup). Add a `steppe qpfstats` CLI (reuse the flag helpers + emitter) + a steppe.qpfstats binding. Gate: a cli_qpfstats ctest + a pytest reproducing golden_fit0_qpfstats_readf2.csv at the tier. Build + full STEPPE_THOROUGH ctest. SANITY: cli_qpfstats reproduces the golden; CpuBackend oracle == CudaBackend; existing goldens/ctest stay green. Report files, the GPU-bound design (no host block loop), the reuse (file:line), the gate, the FULL ctest. Do NOT commit. BAD/NON-trivial blocker -> STOP + report (do NOT revert).',
].join('\n'), { label: 'implement:qpfstats', phase: 'Implement run_qpfstats (oracle-first + on-device) + CLI + binding + build' })
if (fixer === null) { log('--- fixer died — HALT'); return { halted: true, design } }
await tryAgent(['BUILD-REPAIR for qpfstats. Accumulated edits (do NOT clean/revert/destroy; git stash only if forced). Reach a CLEAN Release build (-DSTEPPE_BUILD_CLI=ON -DSTEPPE_BUILD_PYTHON=ON) + green ctest, patching only trivial -Werror / CMake / cuSOLVER-cuBLAS-CUB API misuse (VERIFY vs CUDA 13 docs). DO: ' + RSYNC + ' then ' + BUILD + '. Loop up to 5x on trivial errors. NON-trivial -> STOP + report. Report final build + ctest + patches.', STD].join('\n'), { label: 'repair', phase: 'Implement run_qpfstats (oracle-first + on-device) + CLI + binding + build' })

phase('Verify golden + GPU-bound + emulated + commit-or-HALT')
const VERDICT_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['pass','fail_severity','golden_reproduced','gpu_bound','no_host_block_loop','reuses_seams','emulated_fp64','goldens_green','build_clean','commit_hash','stash_ref','note'],
  properties: {
    pass: { type: 'boolean', description: 'true ONLY if steppe qpfstats reproduces the fixture-matched admixtools-R golden at the tier (cli + pytest), the solve is GPU-bound (shared-factor batched, NO host per-block loop, device-resident), reuses the existing seams (no bolt-on), emulated-FP64 default, full ctest green, single-GPU, no synthetic, CpuBackend==CudaBackend' },
    fail_severity: { type: 'string', description: 'if pass=false: minor (move-on) or bad (HALT + defer to user)' },
    golden_reproduced: { type: 'boolean' }, gpu_bound: { type: 'boolean', description: 'the qpfstats solve is GPU-bound (batched cuSOLVER, not a host block loop)' },
    no_host_block_loop: { type: 'boolean', description: 'verified: no host per-jackknife-block solve loop; no host frame materialization' },
    reuses_seams: { type: 'boolean' }, emulated_fp64: { type: 'boolean' }, goldens_green: { type: 'boolean' }, build_clean: { type: 'boolean' },
    commit_hash: { type: 'string' }, stash_ref: { type: 'string' },
    note: { type: 'string', description: 'the golden reproduction + the GPU-bound design + the reuse; on FAIL the blocker + minor-vs-bad' },
  },
}
const verdict = await tryAgent([
  'You are the INDEPENDENT VERDICT for qpfstats (adversarial; hold ALL the standing bars: GPU-bound [no host block loop], reuse-no-bolt-on, emulated-first, on-device-no-bounce). design:\n<<<\n' + JSON.stringify(design) + '\n>>>\nimplementer:\n<<<\n' + fixer + '\n>>>', STD, '',
  'DO: (1) git diff review — the solve is the shared-factor batched cuSOLVER path (NO host per-jackknife-block loop, NO host frame materialization), device-resident, reuses the existing seams (no parallel bolt-on), emulated-FP64 default + native carve-out, CpuBackend oracle present. (2) ' + BUILD + ' — STEPPE_THOROUGH ctest green; cli_qpfstats + pytest reproduce the fixture-matched admixtools-R golden at the tier; CpuBackend==CudaBackend. (3) confirm GPU-bound (the qpfstats compute is batched on-device; if a real hot path exists, sample nvidia-smi), single-GPU, no synthetic, no golden regen beyond the one fixture-matched golden. PASS only if all hold. ',
  'ON PASS: cd ' + R + ' && git add ONLY the new golden + new/changed source/test/cmake/binding/doc (NEVER git add dot; never aadr/ atlas_results/ handoff-*.md), commit (STEP3 qpfstats: joint full-basis f-stat estimator `steppe qpfstats` + steppe.qpfstats binding — GPU-bound shared-factor batched cuSOLVER solve [reformulated from the AT2 host block loop, no host frame], reuse the solve/precision seam, emulated-FP64; fixture-matched admixtools-R golden) ending: Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com> . Capture the hash. Update docs (RESUME/TODO: qpfstats done; next qpGraph). ',
  'ON BAD (golden mismatch beyond tier / CPU-bound / structural / oracle ambiguity): DO NOT git checkout/clean, DO NOT revert. ' + STASH + ' "wip:qpfstats-FAILED" (capture the ref). Classify fail_severity=bad + the blocker for the user to decide. Return the structured verdict.',
].join('\n'), { schema: VERDICT_SCHEMA, label: 'verify:qpfstats', phase: 'Verify golden + GPU-bound + emulated + commit-or-HALT' })
if (verdict === null) { log('--- verdict died — HALT'); return { halted: true, design } }
if (verdict.pass) log('+++ qpfstats ' + verdict.commit_hash + ' — ' + verdict.note)
else log('--- qpfstats FAILED [' + verdict.fail_severity + '] — stashed ' + verdict.stash_ref + ' — HALT+defer — ' + verdict.note)
return { design, verdict }
