export const meta = {
  name: 'qpfstats-perf',
  description: 'FIX the qpfstats scale perf — it is 59s at 40 pops with the GPU only ~50% busy (100/0 alternation) because WORK IS ON THE CPU. MEASURED breakdown (40 pops, 3987 inds, real AADR): ~14s genotype decode (GPU idle) + ~38s where the GPU ALTERNATES 100%/0% every second + trailing. ROOT CAUSE (verified in code): the block-JACKKNIFE for the smoothed tensor runs on the HOST — src/core/stats/qpfstats.cpp matrix_jackknife_est_col (a host long-double per-block loop) is called PER popcomb, i.e. ~305k combos x 711 blocks = ~217M long-double iterations on ONE CPU core, interleaved with the GPU reduce + GPU solve phases (the 100/0 alternation). The doc comment "NO host per-block loop" held for the SOLVE but the JACKKNIFE/recenter was left on the host. SECONDARY: (a) the genotype-f4 reduce kernel (dstat_block_reduce, reused from qpDstat) is one-thread-per-(combo,block) and RE-READS the same pops allele freqs once per combo -> memory-bound at 305k combos (should load the npop pops per SNP ONCE, form the C(npop,2) pairwise differences, then the 305k combo products reuse those); (b) the ~14s decode (3987 inds) does not overlap with compute. THE FIX: (1) move the per-combo block-jackknife (matrix_jackknife_est over [npopcomb x n_block]) ONTO the GPU as a batched kernel (embarrassingly parallel over the ~305k combos; reduces over blocks) — kill the host long-double loop; (2) eliminate ANY remaining host-in-the-loop in the smoothing/recenter (one batched device pass, no per-block / per-combo host orchestration); (3) consider the pairwise-difference-reuse reduce kernel to make the reduce compute-bound not memory-bound; (4) overlap the decode with compute where feasible. GOAL: the 40-pop wall-clock drops hard and the GPU stays ~continuously busy (no 100/0). GOLDEN-EXACT: the 9-pop qpfstats golden MUST still match at rtol 1e-6 (the long-double host jackknife -> GPU double/accurate accumulation must reproduce it at the tier) + CpuBackend==CudaBackend. REQUIREMENTS (locked): GPU-FIRST + GPU-BOUND (no host hot loop; the jackknife is the offender — move it on-device); VERIFY (real code file:line + nsys/the util timeline before+after); REUSE no parallel bolt-on; EmulatedFp64 where matmul-heavy + native carve-out (cancellation: the jackknife/recenter accumulation may need careful/long-double-equivalent accumulation to hold the golden tier); SINGLE-GPU --device 0 (multi-GPU PARKED); CUDA 13+ (verify any new kernel + CUB vs docs); KEEP ON-DEVICE no warts/bouncing. Discipline: diagnose (GATE — pinpoint EVERY host-serialized step + confirm the fix preserves the golden) -> implement (move the jackknife on-device + the reduce/decode fixes) -> verify (golden 1e-6 + before/after wall+util at 40 pops + ctest) -> commit. FAIL-PROTOCOL: verify->commit on green; on BAD (golden breaks / not actually faster / not GPU-continuous) HALT + report + defer; NEVER silently fail/revert; on failure git stash push -u + HALT.',
  phases: [ { title: 'Diagnose the host serialization precisely (GATE: every CPU hot step + golden-preserving fix plan)' }, { title: 'Implement: move the jackknife on-device + the reduce/decode fixes + build' }, { title: 'Verify golden 1e-6 + before/after 40-pop wall+util (GPU continuous) + commit-or-HALT' } ],
}

const R = '/home/suzunik/steppe'
const SSH = 'ssh box5090'
const PATHENV = 'export PATH=/usr/local/cuda/bin:$PATH && export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH && ulimit -c 0'
const CORECLEAN = 'rm -f /var/lib/vastai_kaalia/data/core-* 2>/dev/null'
const RSYNC = 'rsync -az --delete-after --exclude .git --exclude build --exclude build-rel --exclude aadr --exclude atlas_results -e ssh ' + R + '/ box5090:/workspace/steppe/'
const BUILD = SSH + " 'cd /workspace/steppe && " + PATHENV + " && " + CORECLEAN + " && cmake -S . -B build-rel -GNinja -DCMAKE_BUILD_TYPE=Release -DSTEPPE_BUILD_CLI=ON -DSTEPPE_BUILD_PYTHON=ON >/tmp/cfg.log 2>&1 && cmake --build build-rel 2>&1 | tail -25 && echo === CTEST === && STEPPE_THOROUGH=1 ctest --test-dir build-rel --output-on-failure 2>&1 | tail -20; " + CORECLEAN + "'"
const STASH = 'cd ' + R + ' && git stash push -u -m'
const TGENO = '/workspace/data/aadr/raw/v66.p1_HO.aadr.patch.PUB'
const POPS40 = 'Spanish,Han,YRI,Sweden_Viking,Poland_IA,Czechia_EBA_Unetice,Spain_C,ESN,TSI,GWD,CHS,CHB,JPT,ITU,Austria_N_LBK,PUR,STU,CEU,Russian,Tibetan,LWK,CLM,BEB,ACB,French,FIN,GIH,PJL,KHV,Turkey_N,Druze,Palestinian,Mongol,Kazakh,Sweden_N,Scotland_N,Spain_EBA,England_IA,Denmark_Viking,MSL'
// per-second GPU sm% util timeline + wall, for a 40-pop qpfstats run to <OUTDIR>
const MEASURE = (out) => SSH + " 'cd /workspace/steppe && " + PATHENV + " && nvidia-smi dmon -s u -d 1 -c 120 > /tmp/tl.log 2>&1 & DM=$!; /usr/bin/time -v ./build-rel/bin/steppe qpfstats --prefix " + TGENO + " --pops \"" + POPS40 + "\" --out-dir " + out + " >/dev/null 2>/tmp/qt.log; kill $DM 2>/dev/null; echo WALL:; grep Elapsed /tmp/qt.log; echo UTIL_TIMELINE:; grep -vE \"#|Idx\" /tmp/tl.log | awk \"{printf \\$2\\\" \\\"}\"; echo; echo BUSY_VS_IDLE:; grep -vE \"#|Idx\" /tmp/tl.log | awk \"{if(\\$2==0)z++;else nz++}END{print \\\"idle=\\\"z\\\"s busy=\\\"nz\\\"s\\\"}\"'"

const STD = [
  'PROJECT: steppe = GPU/CUDA-13 reimplementation of ADMIXTOOLS 2 + qpAdm. Branch phase2-fit-engine == main @ 621a7db. qpfstats (dd8f99a) is GOLDEN-CORRECT (9-pop genotype golden rtol 1e-6) but SLOW at scale: 40 pops = 59s wall, GPU only ~50% busy (measured 100/0 per-second alternation). This is a PERF fix; correctness must NOT regress.',
  'MEASURED ROOT CAUSE (verified): the block-JACKKNIFE for the smoothed tensor is on the HOST. src/core/stats/qpfstats.cpp matrix_jackknife_est_col is a host long-double per-block loop called PER popcomb -> ~305k combos x 711 blocks = ~217M long-double iterations on ONE CPU core, interleaved with the GPU reduce/solve = the 100/0 alternation. The "NO host per-block loop" comment held for the SOLVE but the JACKKNIFE/recenter stayed on the host. The genotype-f4 reduce (dstat_block_reduce) is also one-thread-per-(combo,block) re-reading pops per combo (memory-bound at 305k). Decode ~14s does not overlap.',
  'THE FIX (GPU-bound, golden-preserving): (1) move the per-combo block-jackknife (matrix_jackknife_est over the [npopcomb x n_block] numer/cnt) ONTO the GPU — a batched kernel, embarrassingly parallel over the ~305k combos, reducing over blocks; kill the host long-double loop. WATCH the accumulation: the host uses long double; the GPU must reproduce the 9-pop golden at rtol 1e-6 (use accurate/compensated or sufficient-precision accumulation, NOT a naive lossy sum). (2) eliminate any remaining host-in-the-loop in the smoothing/recenter so it is ONE batched device pass (no per-block/per-combo host orchestration). (3) OPTIONAL if it is the reduce that dominates the GPU busy time: a pairwise-difference-reuse reduce kernel (load npop pops per SNP once, form C(npop,2) diffs, the combo products reuse them) -> compute-bound not memory-bound. (4) overlap the decode with compute if feasible.',
  'STANDING REQUIREMENTS (locked): GPU-FIRST + GPU-BOUND (no host hot loop); VERIFY (file:line + the before/after util timeline + nsys if useful); REUSE no parallel bolt-on; EmulatedFp64 where matmul-heavy + native/long-double-equivalent carve-out for the jackknife cancellation; SINGLE-GPU --device 0 (multi-GPU PARKED); CUDA 13+ (verify any new kernel/CUB vs docs); KEEP ON-DEVICE no warts/bouncing.',
  'GOLDEN GATE (non-negotiable): the 9-pop qpfstats genotype golden (tests/reference/goldens/at2/golden_qpfstats_geno) MUST still reproduce at rtol 1e-6 + CpuBackend==CudaBackend + the full STEPPE_THOROUGH ctest stays green. A faster-but-wrong result is a FAIL.',
  'PERF GATE: re-measure the 40-pop run (real AADR, the 40 pops in the workflow) BEFORE (current 59s) and AFTER; AFTER must be materially faster AND the GPU util timeline must be ~continuously busy (the 100/0 alternation gone). Report both timelines.',
  'FAIL-PROTOCOL (USER-MANDATED, STRICT): NEVER git checkout -- . / git clean -fd. verify->commit ONLY on green (golden held + materially faster + GPU-continuous). On a BAD result (golden breaks, not faster, still serialized) HALT + report + DEFER — do NOT silently fail/revert. On any failure ' + STASH + ' "wip:qpfstats-perf-FAILED-<reason>" + HALT.',
  'SINGLE-GPU --device 0. RELEASE build-rel. REAL AADR; no synthetic. The 40-pop set + TGENO ' + TGENO + '. Box ' + SSH + '; nvcc -> ' + PATHENV + '. §4 layering. nothing builds locally.',
].join('\n')

async function tryAgent(p, opts) { let r = await agent(p, opts); for (let i=0;i<2&&r===null;i++){ log(opts.label+': transient null/500 — retry '+(i+1)); r = await agent(p, {...opts, label: opts.label+':retry'+(i+1)}) } return r }

phase('Diagnose the host serialization precisely (GATE: every CPU hot step + golden-preserving fix plan)')
const DESIGN_SCHEMA = {
  type: 'object', additionalProperties: false, required: ['feasible','serialization_causes','jackknife_gpu_plan','accumulation_golden_risk','reduce_kernel_plan','decode_overlap','before_measure','blocker','notes'],
  properties: {
    feasible: { type: 'boolean', description: 'true iff the host serialization can be moved on-device GPU-bound while preserving the 9-pop golden at rtol 1e-6. false -> HALT + defer' },
    serialization_causes: { type: 'string', description: 'EVERY host-serialized step in run_qpfstats (file:line) confirmed as a cause of the 100/0 alternation — the per-combo host jackknife, any recenter loop, any per-block re-solve' },
    jackknife_gpu_plan: { type: 'string', description: 'the on-device batched jackknife design (parallel over ~305k combos, reduce over blocks); the kernel/CUB shape' },
    accumulation_golden_risk: { type: 'string', description: 'how the GPU accumulation reproduces the host long-double matrix_jackknife_est_col at rtol 1e-6 (compensated/double-double/sufficient precision); the risk + mitigation' },
    reduce_kernel_plan: { type: 'string', description: 'whether the dstat reduce is the GPU-busy bottleneck + the pairwise-difference-reuse plan if so (or defer it)' },
    decode_overlap: { type: 'string', description: 'whether/how the ~14s decode overlaps compute (or is left, with rationale)' },
    before_measure: { type: 'string', description: 'the BEFORE 40-pop wall + util timeline (re-confirm 59s / 100-0)' },
    blocker: { type: 'string', description: 'if NOT feasible: the blocker (HALT + defer)' },
    notes: { type: 'string' },
  },
}
const design = await tryAgent([
  'You are diagnosing + planning the qpfstats perf fix (verify-before-implement; NO code changes). READ the FULL src/core/stats/qpfstats.cpp (run_qpfstats body + matrix_jackknife_est_col + the smoothing/recenter calls), the ComputeBackend::qpfstats_smooth + dstat_block_reduce in src/device/cuda/cuda_backend.cu, the CpuBackend equivalents. PINPOINT every host-serialized step causing the measured 100/0 GPU alternation (the per-combo host jackknife is the prime suspect; confirm + find any others). Plan: move the per-combo block-jackknife ON-DEVICE (batched over ~305k combos), preserving the host long-double result at rtol 1e-6 (state the accumulation strategy). Assess the reduce kernel (memory-bound?) + the decode overlap. RE-MEASURE the BEFORE 40-pop baseline (run: ' + MEASURE('/tmp/qpfs_before') + '). VERIFY any new kernel/CUB API vs the CUDA 13.x docs. Return the structured plan. If the host jackknife cannot be moved on-device without breaking the golden, feasible=false + blocker (HALT + defer).', STD,
].join('\n'), { schema: DESIGN_SCHEMA, label: 'diagnose:qpfsperf', phase: 'Diagnose the host serialization precisely (GATE: every CPU hot step + golden-preserving fix plan)' })
if (design === null) { log('--- diagnose died — HALT'); return { halted: true } }
if (!design.feasible) { log('--- qpfstats-perf STRUCTURAL (HALT + defer): ' + design.blocker); return { halted: true, deferred: true, design } }
log('qpfstats-perf feasible; causes: ' + String(design.serialization_causes).slice(0,140))

phase('Implement: move the jackknife on-device + the reduce/decode fixes + build')
const fixer = await tryAgent([
  'You are implementing the qpfstats perf fix per this plan (move the host jackknife on-device + kill every host hot loop; GOLDEN-EXACT):\n<<<\n' + JSON.stringify(design) + '\n>>>\n\nDo NOT commit. Do NOT git checkout/clean (git stash if forced).', STD, '', 'DEV LOOP: edit locally; ' + RSYNC + '; build+ctest (' + BUILD + ').', '',
  'IMPLEMENT: move the per-combo block-jackknife (matrix_jackknife_est) ON-DEVICE as a batched kernel over the ~305k combos (reduce over blocks), reproducing the host long-double result at rtol 1e-6 (the stated accumulation strategy); eliminate any remaining host-in-the-loop in the smoothing/recenter (one batched device pass); apply the reduce-kernel / decode-overlap fixes per the plan. Reuse the existing seams (no bolt-on); emulated where matmul-heavy. Build + full STEPPE_THOROUGH ctest. SANITY: the 9-pop golden still reproduces at the tier (cli + parity); a quick 40-pop run shows the GPU now stays ~continuously busy (no 100/0) and is materially faster. Report files, the on-device jackknife, the build, the golden re-check, your 40-pop util/wall observation. Do NOT commit. BAD/NON-trivial blocker (golden breaks) -> STOP + report (do NOT revert).',
].join('\n'), { label: 'implement:qpfsperf', phase: 'Implement: move the jackknife on-device + the reduce/decode fixes + build' })
if (fixer === null) { log('--- fixer died — HALT'); return { halted: true, design } }
await tryAgent(['BUILD-REPAIR for the qpfstats perf fix. Accumulated edits (do NOT clean/revert/destroy; git stash only if forced). Reach a CLEAN Release build + green STEPPE_THOROUGH ctest (the 9-pop qpfstats golden MUST hold), patching only trivial errors. DO: ' + RSYNC + ' then ' + BUILD + '. Loop up to 5x. NON-trivial / golden breaks -> STOP + report. Report build + ctest + patches.', STD].join('\n'), { label: 'repair', phase: 'Implement: move the jackknife on-device + the reduce/decode fixes + build' })

phase('Verify golden 1e-6 + before/after 40-pop wall+util (GPU continuous) + commit-or-HALT')
const VERDICT_SCHEMA = {
  type: 'object', additionalProperties: false,
  required: ['pass','fail_severity','golden_held','before_wall','after_wall','gpu_continuous','speedup','jackknife_on_device','goldens_green','commit_hash','stash_ref','note'],
  properties: {
    pass: { type: 'boolean', description: 'true ONLY if the 9-pop qpfstats golden still reproduces at rtol 1e-6 (CpuBackend==CudaBackend, ctest green), the 40-pop run is MATERIALLY faster, AND the GPU util is ~continuous (no 100/0 alternation), single-GPU, real AADR' },
    fail_severity: { type: 'string', description: 'if pass=false: minor or bad (HALT + defer)' },
    golden_held: { type: 'boolean', description: 'the 9-pop golden still matches at rtol 1e-6 (correctness NOT regressed)' },
    before_wall: { type: 'string', description: 'the BEFORE 40-pop wall (~59s) + util shape' },
    after_wall: { type: 'string', description: 'the AFTER 40-pop wall + util shape (must be GPU-continuous)' },
    gpu_continuous: { type: 'boolean', description: 'the 100/0 alternation is gone; GPU stays busy through the compute phase' },
    speedup: { type: 'string', description: 'the measured speedup factor at 40 pops' },
    jackknife_on_device: { type: 'boolean', description: 'the per-combo block-jackknife now runs on the GPU, not the host' },
    goldens_green: { type: 'boolean' },
    commit_hash: { type: 'string' }, stash_ref: { type: 'string' },
    note: { type: 'string', description: 'before/after numbers + what moved on-device; on FAIL the blocker + minor-vs-bad' },
  },
}
const verdict = await tryAgent([
  'You are the INDEPENDENT VERDICT for the qpfstats perf fix (adversarial; hold BOTH bars: the 9-pop golden at rtol 1e-6 AND materially-faster-with-GPU-continuous). plan:\n<<<\n' + JSON.stringify(design) + '\n>>>\nimplementer:\n<<<\n' + fixer + '\n>>>', STD, '',
  'DO: (1) git diff review — the per-combo block-jackknife now runs on-device (batched, not the host long-double loop), no remaining host hot loop, golden-preserving accumulation, reuses seams. (2) ' + BUILD + ' — STEPPE_THOROUGH ctest green; the 9-pop qpfstats golden reproduces at rtol 1e-6; CpuBackend==CudaBackend. (3) THE PERF GATE: re-measure the 40-pop run AFTER (' + MEASURE('/tmp/qpfs_after') + ') and confirm it is materially faster than ~59s AND the util timeline is ~continuously busy (no 100/0). (4) single-GPU, real AADR. PASS only if the golden HELD and it is faster + GPU-continuous. ',
  'ON PASS: cd ' + R + ' && git add ONLY the changed source/test/cmake (NEVER git add dot; never aadr/ atlas_results/), commit (perf(qpfstats): move the block-jackknife on-device (batched over popcombs) — kill the host long-double per-combo loop that left the GPU ~50% idle (100/0); 40 pops <before>->after, GPU now continuous; 9-pop golden held at rtol 1e-6) ending: Co-Authored-By: Claude Opus 4.8 (1M context) <noreply@anthropic.com> . Capture the hash. Update docs (the qpfstats perf number on real AADR). ',
  'ON BAD (golden breaks / not faster / still serialized): DO NOT git checkout/clean, DO NOT revert. ' + STASH + ' "wip:qpfstats-perf-FAILED" (capture the ref). Classify fail_severity + the blocker for the user. Return the structured verdict.',
].join('\n'), { schema: VERDICT_SCHEMA, label: 'verify:qpfsperf', phase: 'Verify golden 1e-6 + before/after 40-pop wall+util (GPU continuous) + commit-or-HALT' })
if (verdict === null) { log('--- verdict died — HALT'); return { halted: true, design } }
if (verdict.pass) log('+++ qpfstats-perf ' + verdict.commit_hash + ' — ' + verdict.speedup + ' — ' + verdict.note)
else log('--- qpfstats-perf FAILED [' + verdict.fail_severity + '] — stashed ' + verdict.stash_ref + ' — HALT+defer — ' + verdict.note)
return { design, verdict }
