export const meta = {
  name: 'research-pycuda',
  description: 'Research PyCUDA (CUDA 13+) viability + how/whether it applies to steppe\'s Python access layer — the user raised it as an avenue vs the planned nanobind C++ in-process binding. HONEST/adversarial: PyCUDA is for DRIVING the CUDA driver API / launching kernels FROM Python (a different problem than steppe\'s, where the kernels are already COMPILED in steppe_device and the binding just needs to call the finished C++ run_qpadm). The genuinely useful angle to evaluate is GPU INTEROP (could PyCUDA / __cuda_array_interface__ / DLPack / cuda-python let a user hand steppe a device array zero-copy, or get the f2 tensor back as a GPU array?) + PyCUDA\'s real CUDA-13 maintenance/viability vs the official cuda-python/cuda.core. 4 parallel web-research lenses -> a synthesis verdict (use it / do not / use it only for interop) for the step-2/M(py-1) bindings. Writes /tmp/pycuda-viability.md (NOT in the repo — the concurrent CLI build CLEANs the repo tree; the orchestrator commits the doc into docs/research/ afterward). NO box, NO repo edits, NO git.',
  phases: [ { title: 'Research', detail: '4 parallel lenses: PyCUDA+CUDA13 status / fit-vs-nanobind / GPU-interop (CAI/DLPack/cuda-python) / cost-benefit' }, { title: 'Synthesize', detail: 'verdict doc -> /tmp/pycuda-viability.md' } ],
}

const R = '/home/suzunik/steppe'
const OUT = '/tmp/pycuda-viability.md'

const STD = [
  'PROJECT: steppe = GPU/CUDA-13/Blackwell C++20 reimplementation of ADMIXTOOLS 2 + qpAdm. The compute (f2 GEMMs, qpAdm/qpWave/rotation kernels, cuBLAS/cuSOLVER) is ALL compiled C++/CUDA in steppe_device, orchestrated in C++; the Python binding\'s job (step 2 / M(py-1)) is a THIN layer that calls the finished public C++ API (run_qpadm/run_qpwave/run_qpadm_search in include/steppe/qpadm.hpp) + marshals numpy<->results. The planned binding is nanobind (ADR-0002) linking the C++ in-process. The f2 interchange is DeviceF2Blocks (resident in VRAM) / F2BlockTensor (host).',
  'THE QUESTION (the user raised PyCUDA as an avenue): is PyCUDA viable on CUDA 13+, and does it APPLY to steppe\'s Python access layer? Be HONEST + adversarial — do not rubber-stamp it. PyCUDA exposes the CUDA DRIVER API to Python (device malloc, NVRTC/nvcc kernel compile+launch, streams). steppe does NOT need to launch kernels from Python (its kernels are compiled in C++). So evaluate: (a) is PyCUDA the wrong tool for the BINDING mechanism (vs nanobind calling the C++)? (b) is there a real INTEROP angle — zero-copy device-array handoff (a user with CuPy/PyTorch/numba GPU data passing into steppe, or getting the f2 tensor back as a GPU array) — and is PyCUDA the right vehicle for THAT vs __cuda_array_interface__ (CAI) / DLPack / the official cuda-python (cuda.core)? (c) PyCUDA\'s CUDA-13 maintenance/viability + context-ownership conflicts (PyCUDA owns a CUDA context from Python while steppe owns its own context/streams/handles in C++ — two owners = trouble?).',
  'READ-ONLY: web research (ToolSearch select:WebSearch,WebFetch) + cite real sources/dates. NO box, NO repo edits, NO git. The deliverable is /tmp/pycuda-viability.md. No fabrication; flag uncertainty.',
].join('\n')

phase('Research')
const LENSES = [
  { key: 'pycuda-status', focus: 'PyCUDA itself + its CUDA 13 status. What PyCUDA is (driver-API wrapper, GPUArray, SourceModule/NVRTC kernel compile+launch, contexts/streams), its current maintenance state + release cadence (is it actively maintained in 2026?), and its CONFIRMED compatibility with CUDA 13.x (Blackwell sm_120) — does it build/run on CUDA 13, any known issues? Compare to the OFFICIAL NVIDIA cuda-python / cuda.core (the NVIDIA-blessed Python CUDA bindings) which are the modern path. Cite versions/dates/issues.' },
  { key: 'fit-vs-nanobind', focus: 'Does PyCUDA fit steppe\'s BINDING need vs nanobind? steppe wants to expose a FINISHED compiled C++ engine (run_qpadm etc.) to Python — a thin call-into-C++ + numpy marshalling layer (nanobind, ADR-0002). PyCUDA is for writing/launching GPU kernels FROM Python, which steppe does NOT do. Assess: would using PyCUDA mean Python owns a CUDA context while steppe_device owns its own context/streams/cuBLAS/cuSOLVER handles in C++ — a two-context-owner conflict? Can PyCUDA even call steppe\'s compiled kernels (no — they are internal C++ symbols)? Conclude whether PyCUDA is the wrong layer for the binding mechanism and nanobind-calling-C++ is correct.' },
  { key: 'interop-zerocopy', focus: 'The REAL interop angle: zero-copy GPU-array handoff between steppe and the Python GPU ecosystem (CuPy / PyTorch / numba / RAPIDS). steppe holds the f2 as a DeviceF2Blocks (VRAM); a user might want to (1) pass a device array INTO steppe, or (2) get the resident f2 tensor OUT as a GPU array without a host round-trip. What is the right mechanism for that — the __cuda_array_interface__ (CAI) protocol, DLPack, or cuda-python? Where does PyCUDA fit (PyCUDA GPUArray supports CAI)? Is this interop even wanted for steppe\'s precompute-once/fit-many flow (the f2 dir is the interchange; is a GPU-array handoff valuable, e.g. for a user keeping f2 resident across many fits from Python)? Cite the CAI/DLPack specs + which libs support them.' },
  { key: 'cost-benefit', focus: 'HONEST cost/benefit + recommendation for steppe\'s step-2/M(py-1) bindings. Given the plan is nanobind-linking-C++-in-process (ADR-0002): is there ANY part PyCUDA improves, or is it a solution looking for a problem here? Consider: dependency weight (PyCUDA adds a Python CUDA stack alongside steppe\'s own), context/stream conflicts, maintenance risk (PyCUDA vs cuda-python), and whether a CAI/DLPack interop seam (NOT PyCUDA per se) is worth adding to the nanobind module for GPU-array users. Land a clear verdict: (A) nanobind-only, no PyCUDA; (B) nanobind + a CAI/DLPack interop seam (no PyCUDA); (C) PyCUDA has a real role (specify). Most likely A or B — argue it from the evidence.' },
]
const found = await parallel(LENSES.map(L => () => agent([
  'You are a CUDA/Python-interop research analyst evaluating PyCUDA for steppe, HONEST + adversarial: ' + L.focus, '', STD,
  '', 'Load web tools (ToolSearch select:WebSearch,WebFetch), run targeted searches, FETCH primary sources (PyCUDA docs/repo, NVIDIA cuda-python docs, the CAI/DLPack specs, CUDA 13 release notes). Cite real URLs + dates. Return your findings + a per-lens lean (does PyCUDA help here or not). No fabrication.',
].join('\n'), { label: 'research:' + L.key, phase: 'Research' })))

phase('Synthesize')
const report = await agent([
  'You are the lead synthesizer of the PyCUDA-for-steppe viability report. Combine the 4 lenses into an honest verdict for the step-2/M(py-1) bindings.', '', STD,
  '', 'THE LENSES:\n' + found.filter(Boolean).map((f,i)=>'### '+LENSES[i].key+'\n'+f).join('\n\n'),
  '', 'WRITE ' + OUT + ' (in /tmp, NOT the repo) with: (1) WHAT PyCUDA is + its CUDA-13 viability (cited). (2) DOES IT FIT steppe\'s binding need — the honest answer (binding = nanobind-calling-C++; PyCUDA is for Python-launched kernels steppe does not have; the two-context-owner problem). (3) THE INTEROP QUESTION — is zero-copy GPU-array handoff (CAI/DLPack/cuda-python) worth a seam in the nanobind module, and is PyCUDA the right vehicle for it (vs CAI/DLPack directly)? (4) VERDICT: A nanobind-only / B nanobind + CAI-or-DLPack interop seam / C PyCUDA-has-a-role — with the rationale + what (if anything) to add to the M(py-1) plan. (5) sources. Use the Write tool to write ' + OUT + '. Do NOT git-commit, do NOT touch the repo. Return the headline verdict + the 1-line recommendation for the bindings.',
].join('\n'), { label: 'synthesize:pycuda', phase: 'Synthesize' })
log('pycuda research -> /tmp/pycuda-viability.md: ' + String(report).slice(0, 200))
return { report }
